<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>TaskManagement.API.Migrations.Oracle</AssemblyName>
    <RootNamespace>TaskManagement.API.Migrations.Oracle</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\TaskManagement.Data\TaskManagement.Data.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.8">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Oracle.EntityFrameworkCore" Version="8.23.60" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\TaskManagement.API\Migrations\*.cs"
             Link="Migrations\%(Filename)%(Extension)" />
  </ItemGroup>

</Project>
